### PR TITLE
Sway to regolith migration

### PR DESCRIPTION
**Pull request by hypergig**
Obligatory very sad. The following would need to happen for me to come back to sway:
* JetBrains apps start supporting wayland natively
* Zoom screen share works in sway
* Electron starts supporting wayland natively
  * OR xwayland gets better native scaling ie no more blockyness / blurriness

### CODE REVIEW

**Comment by hypergig** [comment]
related to bullet 1: https://github.com/swaywm/sway/issues/3007#issuecomment-611489323

**Comment by hypergig** [comment]
related to bullet 1: https://github.com/swaywm/sway/issues/3007

**Comment by hypergig** [comment]
related to bullet 3: https://github.com/swaywm/wlroots/pull/2064

**Comment by hypergig** [comment]
related to bullet 2: https://github.com/swaywm/sway/issues/5083

**Comment by hypergig** [comment]
related to bullet 2: https://github.com/swaywm/sway/issues/4358

**Comment by fourstepper** [comment]
What's the advantage of using i3 (regolith) over linux even in the scenario of subpar XWayland performance in certain apps?

**Comment by hypergig** [comment]
@fourstepper it pained me to switch over but ultimately I needed to because I needed zoom screen share to work. Due to the quarantine, my whole company is now remote so this became a dealbreaker for me... 

More specifically to your question, I found XWayland performance ok, I often didn't know when an app was is XWayland. That is, until I moved to my hdmi laptop screen and everything got blocky (or blurry before the nearest neighbor release).

The Jetbrains issue is 100% on them not dealing with subwindows and menus well. That would most likely be a dealbreaker now that I do more golang stuff and there aren't any really great golang IDEs out there beside the Jetbrains offerings.

**Pull request merged**
